namespace Clearinet.CompatShim;

/// <summary>
/// Fiddler's <c>SessionFlags</c> bit flags. Names, values and meanings are
/// from Telerik's published FiddlerCore API reference, so code that stores
/// or compares the numeric value behaves the same as it did under Fiddler.
/// </summary>
[Flags]
public enum SessionFlags
{
    /// <summary>No flags are set.</summary>
    None = 0,

    /// <summary>The request originally arrived with a URL specifying the HTTPS protocol.</summary>
    IsHTTPS = 1,

    /// <summary>The request originally arrived with a URL specifying the FTP protocol.</summary>
    IsFTP = 2,

    /// <summary>Ignore this traffic; do not buffer, store, or call event handlers.</summary>
    Ignored = 4,

    /// <summary>The client pipe was reused.</summary>
    ClientPipeReused = 8,

    /// <summary>The server pipe was reused.</summary>
    ServerPipeReused = 16,

    /// <summary>The request was transmitted to the server when its headers were complete.</summary>
    RequestStreamed = 32,

    /// <summary>The response was streamed.</summary>
    ResponseStreamed = 64,

    /// <summary>The request was generated by the tool itself (e.g. a composer).</summary>
    RequestGeneratedByFiddler = 128,

    /// <summary>The response was generated by the tool itself (e.g. AutoResponder).</summary>
    ResponseGeneratedByFiddler = 256,

    /// <summary>This session was loaded from a .SAZ file.</summary>
    LoadedFromSAZ = 512,

    /// <summary>This session was loaded from some other tool.</summary>
    ImportedFromOtherTool = 1024,

    /// <summary>This request was sent to an upstream (CERN) gateway proxy.</summary>
    SentToGateway = 2048,

    /// <summary>This is a "blind" CONNECT tunnel for HTTPS traffic.</summary>
    IsBlindTunnel = 4096,

    /// <summary>This is a CONNECT tunnel which decrypts HTTPS traffic as it flows through.</summary>
    IsDecryptingTunnel = 8192,

    /// <summary>This response was served from a client cache, bypassing the proxy.</summary>
    ServedFromCache = 16384,

    /// <summary>There was an HTTP protocol violation in the client's request.</summary>
    ProtocolViolationInRequest = 32768,

    /// <summary>There was an HTTP protocol violation in the server's response.</summary>
    ProtocolViolationInResponse = 65536,

    /// <summary>The response body was dropped.</summary>
    ResponseBodyDropped = 131072,

    /// <summary>This is a CONNECT tunnel for WebSocket traffic.</summary>
    IsWebSocketTunnel = 262144,

    /// <summary>This request was sent using the SOCKS protocol.</summary>
    SentToSOCKSGateway = 524288,

    /// <summary>The request body was dropped.</summary>
    RequestBodyDropped = 1048576,

    /// <summary>The request was to create an RPC tunnel.</summary>
    IsRPCTunnel = 2097152,

    /// <summary>The session was modified by an AutoResponder rule.</summary>
    IsModifiedByRule = 4194304,

    /// <summary>This is a CONNECT tunnel for gRPC traffic.</summary>
    IsGRPCTunnel = 8388608,

    /// <summary>This is a CONNECT tunnel for HTTP/2 traffic.</summary>
    IsHTTP2OverCONNECTTunnel = 16777216,
}
