<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Clearinet.Compatibility</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Clearinet.ProxyCore\Clearinet.ProxyCore.csproj" />
  </ItemGroup>

</Project>
